name: Script Azure, create VM & install SII
on:
    workflow_dispatch:

jobs:
  CreateResources:
    runs-on: ubuntu-latest
    steps:
      - name: git clone
        uses: actions/checkout@v3
        
      - name: Log in with Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Run Azure sh script
        env:
          INPUT_PASSWORD: ${{ secrets.INPUT_PASSWORD }}
          INPUT_SUB_ID: ${{ secrets.INPUT_SUB_ID }}
        run: bash scriptBash.sh
