name: Ejecutar cmdlets de Azure en PowerShell

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v2

      - name: Install AzureRM module
        run: |
          Install-Module -Name Az.ResourceManager -AllowClobber

      - name: Ejecutar script PowerShell
        run: .\script.ps1
