name: Crear VM en Azure y hacer commit

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v2
        
      - name: Log in with Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          enable-AzPSSession: true

      - name: Run Azure PowerShell Script File
        uses: azure/powershell@v1
        env:
            AZURE_VM_USERNAME: ${{ secrets.AZURE_VM_USERNAME }}
            AZURE_VM_PASSWORD: ${{ secrets.AZURE_VM_PASSWORD }}
        with:
          azPSVersion: "latest"
          inlineScript: ./script.ps1